# Generated by Django 4.2.30 on 2026-04-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='recurring_pattern',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='program',
            field=models.CharField(blank=True, choices=[('Bachelor', 'ปริญญาตรีภาคปกติ'), ('Master', 'ปริญญาโท'), ('TEP_TEPE', 'TEP-TEPE'), ('TU_PINE', 'TU-PINE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose_type',
            field=models.CharField(choices=[('Teaching', 'สอนปกติ/ชดเชย/เสริม'), ('Training', 'จัดอบรม/จัดติว')], default='Teaching', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='training_topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
