# Generated by Django 4.2.30 on 2026-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_room_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
